// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiy__X3Kwye9H-em-SkI2nyjYD4_FCnEQ',
    appId: '1:223103352776:web:743240c997530672c3cafd',
    messagingSenderId: '223103352776',
    projectId: 'travelguard-5a487',
    authDomain: 'travelguard-5a487.firebaseapp.com',
    storageBucket: 'travelguard-5a487.firebasestorage.app',
    measurementId: 'G-GX929ZYZLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJx57aY94VspZV2MsvvIjgbLvBHirMNmU',
    appId: '1:223103352776:android:24b7e1a49b5b022fc3cafd',
    messagingSenderId: '223103352776',
    projectId: 'travelguard-5a487',
    storageBucket: 'travelguard-5a487.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo3SElvT7WXFR2SDj6109j9pkM9hs13SA',
    appId: '1:223103352776:ios:14e45f6a587e612ac3cafd',
    messagingSenderId: '223103352776',
    projectId: 'travelguard-5a487',
    storageBucket: 'travelguard-5a487.firebasestorage.app',
    iosClientId: '223103352776-94bvmto983j4n7u46ce2v9aavvbf3dp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo3SElvT7WXFR2SDj6109j9pkM9hs13SA',
    appId: '1:223103352776:ios:14e45f6a587e612ac3cafd',
    messagingSenderId: '223103352776',
    projectId: 'travelguard-5a487',
    storageBucket: 'travelguard-5a487.firebasestorage.app',
    iosClientId: '223103352776-94bvmto983j4n7u46ce2v9aavvbf3dp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiy__X3Kwye9H-em-SkI2nyjYD4_FCnEQ',
    appId: '1:223103352776:web:ec690c02d0eb96c2c3cafd',
    messagingSenderId: '223103352776',
    projectId: 'travelguard-5a487',
    authDomain: 'travelguard-5a487.firebaseapp.com',
    storageBucket: 'travelguard-5a487.firebasestorage.app',
    measurementId: 'G-KL7XZPTX00',
  );
}
