spring.datasource.url=jdbc:postgresql://db.wtyofjlzjkzjlpdynvay.supabase.co:6543/postgres?prepareThreshold=0 
spring.datasource.username=postgres.wtyofjlzjkzjlpdynvay
spring.datasource.password=travelguard2026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
